
THS_JIEPAN_URL = 'http://stock.10jqka.com.cn/jiepan_list'
NOTICE_START_DATE = '2015-12-28'
NOTICE_END_DATE = '2016-09-22'

NOTICE_PATH_PREFIX = 'D:/ezline/data/notice'
NOTICE_RAW_DATA_PATH = NOTICE_PATH_PREFIX + '/raw'
NOTICE_RAW_URL_NOON_DATA_PATH = NOTICE_RAW_DATA_PATH + '/noon_urls'
NOTICE_RAW_URL_MOURNING_DATA_PATH = NOTICE_RAW_DATA_PATH + '/mourning_urls'
NOTICE_NOON_CONTENT_PATH = NOTICE_PATH_PREFIX + '/content/noon'
NOTICE_MOURNING_CONTENT_PATH = NOTICE_PATH_PREFIX + '/content/mourning'
NOTICE_NOON_DATA_PATH = NOTICE_PATH_PREFIX + '/noon_data'